[package]
name = "timekeeper"
version = "0.1.0"
authors = ["Michael Kainer <michael@kainer.io>"]

[profile.dev]
opt-level = 's'
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1
panic = 'abort'

[profile.release]
opt-level = 's'
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
panic = 'abort'

[lib]
name = "timekeeper"
crate-type = ["bin"]

[dependencies]
my_allocator = { path = "../my_allocator" }
